// Create a sales order + Stripe Checkout Session.
//
// Public endpoint. Two product flows:
//   - one_shot     : open, anyone can buy
//   - wav_premium  : token-gated, the URL is generated by an admin via
//                    /admin/applications detail view and sent manually
//                    (WhatsApp/email) to a validated candidate.
//
// Steps:
//   1. Validate input shape + required consents (CGV, renonciation, RGPD).
//   2. For wav_premium: validate the invitation token (exists, unused,
//      not expired) and link the order back to the application.
//   3. Insert the order row (status='awaiting_payment').
//   4. Create a Stripe Checkout Session, pass our order id as
//      client_reference_id and metadata for the webhook.
//   5. Return the Checkout Session URL.
//
// IP, user-agent and timestamp are captured server-side from the
// request headers — required by L221-28 / GDPR for legal proof.

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import Stripe from "https://esm.sh/stripe@18.5.0";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";
import { getStripeSecretKey, getStripePrices } from "../_shared/stripe-config.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

interface CheckoutPayload {
  product_type: "one_shot" | "wav_premium";
  invitation_token?: string;
  first_name: string;
  last_name: string;
  email: string;
  whatsapp: string;
  billing_address_line1: string;
  billing_address_line2?: string | null;
  billing_postal_code: string;
  billing_city: string;
  billing_country: string;
  consent_cgv: boolean;
  consent_renonciation: boolean;
  consent_rgpd: boolean;
  posthog_id?: string | null;
}

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const CGV_VERSION = "v2026-05-17";

function clientIp(req: Request): string | null {
  return (
    req.headers.get("cf-connecting-ip") ||
    req.headers.get("x-real-ip") ||
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    null
  );
}

function validatePayload(body: unknown): { ok: true; data: CheckoutPayload } | { ok: false; error: string } {
  if (!body || typeof body !== "object") return { ok: false, error: "Corps de requête invalide" };
  const p = body as Record<string, unknown>;

  if (p.product_type !== "one_shot" && p.product_type !== "wav_premium") {
    return { ok: false, error: "product_type invalide" };
  }

  const reqStr = (key: string, label: string, minLen = 1) => {
    const v = typeof p[key] === "string" ? (p[key] as string).trim() : "";
    if (v.length < minLen) return `${label} requis`;
    return null;
  };

  const errors = [
    reqStr("first_name", "Prénom"),
    reqStr("last_name", "Nom"),
    reqStr("email", "Email"),
    reqStr("whatsapp", "Numéro WhatsApp", 5),
    reqStr("billing_address_line1", "Adresse"),
    reqStr("billing_postal_code", "Code postal"),
    reqStr("billing_city", "Ville"),
    reqStr("billing_country", "Pays"),
  ].filter(Boolean);

  if (errors.length) return { ok: false, error: errors[0] as string };

  const email = (p.email as string).trim().toLowerCase();
  if (!EMAIL_RE.test(email)) return { ok: false, error: "Email invalide" };

  if (p.consent_cgv !== true) return { ok: false, error: "Vous devez accepter les CGV" };
  if (p.consent_renonciation !== true)
    return { ok: false, error: "Vous devez renoncer expressément au droit de rétractation" };
  if (p.consent_rgpd !== true)
    return { ok: false, error: "Vous devez consentir au traitement de vos données" };

  return {
    ok: true,
    data: {
      product_type: p.product_type as CheckoutPayload["product_type"],
      invitation_token: typeof p.invitation_token === "string" ? p.invitation_token : undefined,
      first_name: (p.first_name as string).trim(),
      last_name: (p.last_name as string).trim(),
      email,
      whatsapp: (p.whatsapp as string).trim(),
      billing_address_line1: (p.billing_address_line1 as string).trim(),
      billing_address_line2:
        typeof p.billing_address_line2 === "string" && p.billing_address_line2.trim()
          ? (p.billing_address_line2 as string).trim()
          : null,
      billing_postal_code: (p.billing_postal_code as string).trim(),
      billing_city: (p.billing_city as string).trim(),
      billing_country: (p.billing_country as string).trim(),
      consent_cgv: true,
      consent_renonciation: true,
      consent_rgpd: true,
      posthog_id: typeof p.posthog_id === "string" ? p.posthog_id : null,
    },
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  try {
    const body = await req.json().catch(() => null);
    const validation = validatePayload(body);
    if (!validation.ok) {
      return new Response(JSON.stringify({ error: validation.error }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const data = validation.data;

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false } }
    );

    // ── Wav Premium gating ─────────────────────────────────
    let invitation_id: string | null = null;
    let application_id: string | null = null;
    let amount_cents_override: number | null = null;

    if (data.product_type === "wav_premium") {
      if (!data.invitation_token) {
        return new Response(
          JSON.stringify({ error: "Lien d'invitation requis pour Wav Premium" }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const { data: invitation, error: invErr } = await supabase
        .from("wav_premium_invitations")
        .select("id, application_id, amount_cents, expires_at, used_at")
        .eq("token", data.invitation_token)
        .maybeSingle();

      if (invErr || !invitation) {
        return new Response(JSON.stringify({ error: "Lien d'invitation invalide" }), {
          status: 403,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (invitation.used_at) {
        return new Response(JSON.stringify({ error: "Ce lien d'invitation a déjà été utilisé" }), {
          status: 403,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (new Date(invitation.expires_at).getTime() < Date.now()) {
        return new Response(JSON.stringify({ error: "Ce lien d'invitation est expiré" }), {
          status: 403,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      invitation_id = invitation.id;
      application_id = invitation.application_id ?? null;
      amount_cents_override = invitation.amount_cents ?? null;
    }

    // ── Insert sales_orders row ────────────────────────────
    const consent_now = new Date().toISOString();
    const ip = clientIp(req);
    const ua = req.headers.get("user-agent");

    const { data: order, error: orderErr } = await supabase
      .from("sales_orders")
      .insert({
        product_type: data.product_type,
        amount_cents: amount_cents_override,
        currency: "EUR",
        invitation_id,
        application_id,
        first_name: data.first_name,
        last_name: data.last_name,
        email: data.email,
        whatsapp: data.whatsapp,
        billing_address_line1: data.billing_address_line1,
        billing_address_line2: data.billing_address_line2,
        billing_postal_code: data.billing_postal_code,
        billing_city: data.billing_city,
        billing_country: data.billing_country,
        consent_cgv: true,
        consent_cgv_at: consent_now,
        consent_cgv_version: CGV_VERSION,
        consent_renonciation: true,
        consent_renonciation_at: consent_now,
        consent_rgpd: true,
        consent_rgpd_at: consent_now,
        ip_address: ip,
        user_agent: ua,
        posthog_id: data.posthog_id,
        payment_status: "awaiting_payment",
      })
      .select("id")
      .single();

    if (orderErr || !order) {
      console.error("[create-sales-order] insert error:", orderErr);
      return new Response(
        JSON.stringify({ error: `Impossible d'enregistrer la commande: ${orderErr?.message ?? "inconnu"}` }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // ── Stripe Checkout Session ────────────────────────────
    const stripe = new Stripe(getStripeSecretKey(), { apiVersion: "2025-08-27.basil" });
    const prices = getStripePrices();
    const priceId = data.product_type === "one_shot" ? prices.one_shot : prices.wav_premium;

    const origin =
      req.headers.get("origin") ||
      req.headers.get("referer")?.replace(/\/[^/]*$/, "") ||
      "https://fredwav.com";

    const session = await stripe.checkout.sessions.create({
      mode: "payment",
      payment_method_types: ["card"],
      line_items: [{ price: priceId, quantity: 1 }],
      customer_email: data.email,
      client_reference_id: order.id,
      metadata: {
        type: data.product_type === "one_shot" ? "sales_one_shot" : "sales_wav_premium",
        order_id: order.id,
        product_type: data.product_type,
      },
      payment_intent_data: {
        metadata: {
          order_id: order.id,
          product_type: data.product_type,
        },
      },
      success_url: `${origin}/checkout/success?order_id=${order.id}&session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${origin}/checkout/${data.product_type === "one_shot" ? "one-shot" : "wav-premium"}?cancelled=1${
        data.invitation_token ? `&token=${encodeURIComponent(data.invitation_token)}` : ""
      }`,
      locale: "fr",
    });

    // Link the Stripe session id back onto the order for traceability.
    await supabase
      .from("sales_orders")
      .update({ stripe_session_id: session.id })
      .eq("id", order.id);

    return new Response(JSON.stringify({ url: session.url, order_id: order.id }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("[create-sales-order] error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Erreur inconnue" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
