-- ============================================================
-- Sales orders + Wav Premium invitations
-- ============================================================
-- Backs the new /checkout/one-shot (open) and /checkout/wav-premium
-- (token-gated) sales pages. Captures full billing identity,
-- WhatsApp contact and the legal consents required by L221-28 of
-- the French Code de la consommation:
--   - CGV acceptance
--   - Express demand for immediate execution + waiver of the
--     14-day retraction right (B2C)
--   - RGPD processing consent
-- IP address, user-agent, timestamp and CGV version are stored
-- per consent for legal proof in case of dispute / chargeback.
-- ============================================================

-- ── sales_orders ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.sales_orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  -- product
  product_type text NOT NULL
    CHECK (product_type IN ('one_shot', 'wav_premium')),
  amount_cents integer,
  currency text NOT NULL DEFAULT 'EUR',

  -- optional link back to a candidature (Wav Premium flow)
  invitation_id uuid,
  application_id uuid REFERENCES public.wav_premium_applications(id) ON DELETE SET NULL,

  -- customer identity
  first_name text NOT NULL CHECK (trim(first_name) <> ''),
  last_name text NOT NULL CHECK (trim(last_name) <> ''),
  email text NOT NULL CHECK (
    trim(email) <> ''
    AND email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
  ),
  whatsapp text NOT NULL CHECK (trim(whatsapp) <> ''),

  -- billing address
  billing_address_line1 text NOT NULL CHECK (trim(billing_address_line1) <> ''),
  billing_address_line2 text,
  billing_postal_code text NOT NULL CHECK (trim(billing_postal_code) <> ''),
  billing_city text NOT NULL CHECK (trim(billing_city) <> ''),
  billing_country text NOT NULL DEFAULT 'France' CHECK (trim(billing_country) <> ''),

  -- legal consents (each one must be true for the row to exist)
  consent_cgv boolean NOT NULL DEFAULT false
    CHECK (consent_cgv = true),
  consent_cgv_at timestamptz NOT NULL,
  consent_cgv_version text NOT NULL DEFAULT 'v2026-05-17',

  consent_renonciation boolean NOT NULL DEFAULT false
    CHECK (consent_renonciation = true),
  consent_renonciation_at timestamptz NOT NULL,

  consent_rgpd boolean NOT NULL DEFAULT false
    CHECK (consent_rgpd = true),
  consent_rgpd_at timestamptz NOT NULL,

  -- legal proof trail
  ip_address text,
  user_agent text,
  posthog_id text,

  -- Stripe correlation
  stripe_session_id text,
  stripe_payment_intent_id text,
  stripe_customer_id text,
  payment_status text NOT NULL DEFAULT 'awaiting_payment'
    CHECK (payment_status IN ('awaiting_payment', 'paid', 'failed', 'refunded', 'cancelled')),
  paid_at timestamptz,

  -- admin notes (private)
  admin_notes text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sales_orders_email
  ON public.sales_orders (email);
CREATE INDEX IF NOT EXISTS idx_sales_orders_status
  ON public.sales_orders (payment_status);
CREATE INDEX IF NOT EXISTS idx_sales_orders_product
  ON public.sales_orders (product_type);
CREATE INDEX IF NOT EXISTS idx_sales_orders_session
  ON public.sales_orders (stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_created
  ON public.sales_orders (created_at DESC);

-- updated_at trigger
CREATE OR REPLACE FUNCTION public.tg_sales_orders_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_sales_orders_updated_at ON public.sales_orders;
CREATE TRIGGER tg_sales_orders_updated_at
  BEFORE UPDATE ON public.sales_orders
  FOR EACH ROW EXECUTE FUNCTION public.tg_sales_orders_touch_updated_at();

-- ── wav_premium_invitations ─────────────────────────────────
-- Token-gated invitations to the Wav Premium checkout page.
-- Generated by an admin (via /admin/applications detail view)
-- after a candidature has been validated. The token URL is sent
-- to the customer manually (WhatsApp / email), never automatic.
-- Single-use: when the order is created, used_at is set.
CREATE TABLE IF NOT EXISTS public.wav_premium_invitations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  token text NOT NULL UNIQUE,
  application_id uuid REFERENCES public.wav_premium_applications(id) ON DELETE SET NULL,
  amount_cents integer NOT NULL CHECK (amount_cents > 0),
  currency text NOT NULL DEFAULT 'EUR',
  prefill_email text,
  prefill_first_name text,
  prefill_last_name text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  order_id uuid REFERENCES public.sales_orders(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wav_premium_invitations_token
  ON public.wav_premium_invitations (token);
CREATE INDEX IF NOT EXISTS idx_wav_premium_invitations_application
  ON public.wav_premium_invitations (application_id);
CREATE INDEX IF NOT EXISTS idx_wav_premium_invitations_expires
  ON public.wav_premium_invitations (expires_at);

-- ── RLS ─────────────────────────────────────────────────────
ALTER TABLE public.sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wav_premium_invitations ENABLE ROW LEVEL SECURITY;

-- sales_orders: admin only (service role bypasses RLS for inserts via edge function)
CREATE POLICY "Admin full access to sales_orders" ON public.sales_orders
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- wav_premium_invitations: admin only (service role bypasses for token validation in edge function)
CREATE POLICY "Admin full access to wav_premium_invitations" ON public.wav_premium_invitations
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- ── FK back-fill ────────────────────────────────────────────
-- The invitation_id FK on sales_orders is added here once the
-- target table exists.
ALTER TABLE public.sales_orders
  ADD CONSTRAINT sales_orders_invitation_id_fkey
  FOREIGN KEY (invitation_id) REFERENCES public.wav_premium_invitations(id)
  ON DELETE SET NULL;
